import logging
import pathlib
import pickle
import click
from surfclass.randomforest import RandomForest
from surfclass.train import load_training_data

logger = logging.getLogger(__name__)


@click.group()
def train():
    """Train surface classification models using path to training_data."""


@train.command()
@click.argument("trainingdata", type=click.Path(exists=True, file_okay=True), nargs=1)
@click.argument("outputfile", type=click.Path(exists=False, file_okay=True), nargs=1)
def testmodel1(trainingdata, outputfile):
    r"""Trains a new testmodel1 model using an .npz file generated by "surfclass prepare traindata [OPTIONS].

    The traindata should match the model definition.

    Example: surfclass train testmodel1 "testmodel1.npz" "testmodel1.sav"

    """
    (_, classes, features) = load_training_data(trainingdata)

    # This might be a good idea to expose to the CLI.
    num_trees = 200
    # Log inputs
    logger.debug("Training testmodel1 with arguments: %s, %s", trainingdata, outputfile)

    classifier = RandomForest(4, num_trees=num_trees, model=None)
    logger.debug("Training testmodel1...")
    rf_trained = classifier.train(features, classes)

    pickle.dump(rf_trained, open(outputfile, "wb"))
    logger.debug(
        "Training done, written .sav to: %s", pathlib.Path(outputfile).resolve()
    )


@click.argument("trainingdata", type=click.Path(exists=True, file_okay=True), nargs=1)
@click.argument("outputfile", type=click.Path(exists=False, file_okay=True), nargs=1)
def randomforestndvi(trainingdata, outputfile):
    r"""Trains a new randomforestndvi model using an .npz file generated by "surfclass prepare traindata [OPTIONS].

    The traindata should match the model definition.

    Example: surfclass train randomforestndvi "randomforestndvi.npz" "randomforestndvi.sav"

    """
    (_, classes, features) = load_training_data(trainingdata)

    # This might be a good idea to expose to the CLI.
    num_trees = 200
    # Log inputs
    logger.debug(
        "Training randomforestndvi with arguments: %s, %s", trainingdata, outputfile
    )

    classifier = RandomForest(features.shape[1], num_trees=num_trees, model=None)
    logger.debug("Training randomforestndvi")
    rf_trained = classifier.train(features, classes)

    pickle.dump(rf_trained, open(outputfile, "wb"))
    logger.debug(
        "Training done, written .sav to: %s", pathlib.Path(outputfile).resolve()
    )
